export function normalizeName(name: any): string;
export function normalizeNameToAlphaNumericOnly(name: any): string;
export function toStartCase(name: any): any;
export function normalizePathPart(rawPath: any): any;
export function getServiceEndpointRegex(): RegExp;
export function getStackName(): any;
export function getStackChangeSetName(): string;
export function getServiceArtifactName(): string;
export function getFunctionArtifactName(functionName: any): string;
export function getLayerArtifactName(layerName: any): string;
export function getServiceStateFileName(): string;
export function getCompiledTemplateFileName(): string;
export function getCompiledTemplateS3Suffix(): string;
export function getCoreTemplateFileName(): string;
export function getRolePath(): any;
export function getRoleName(): any;
export function getRoleLogicalId(): string;
export function getPolicyName(): {
    'Fn::Join': (string | any[])[];
};
export function getLogGroupLogicalId(functionName: any): string;
export function getLogGroupName(functionName: any): string;
export function getNormalizedFunctionName(functionName: any): string;
export function extractLambdaNameFromArn(functionArn: any): any;
export function extractAuthorizerNameFromArn(functionArn: any): any;
export function getLambdaLogicalId(functionName: any): string;
export function getLambdaFunctionUrlLogicalId(functionName: any): string;
export function getLambdaEventConfigLogicalId(functionName: any): string;
export function getLambdaLayerLogicalId(layerName: any): string;
export function getLambdaLayerPermissionLogicalId(layerName: any, account: any): string;
export function getLambdaLogicalIdRegex(): RegExp;
export function getLambdaVersionLogicalId(functionName: any, sha: any): string;
export function getCodeDeployApplicationLogicalId(): string;
export function getCodeDeployDeploymentGroupLogicalId(): string;
export function getCodeDeployRoleLogicalId(): string;
export function getLambdaProvisionedConcurrencyAliasLogicalId(functionName: any): string;
export function getLambdaSnapStartAliasLogicalId(functionName: any): string;
export function getLambdaProvisionedConcurrencyAliasName(): string;
export function getLambdaSnapStartEnabledAliasName(): string;
export function getLambdaFunctionUrlOutputLogicalId(functionName: any): string;
export function getLambdaVersionOutputLogicalId(functionName: any): string;
export function getLambdaLayerOutputLogicalId(layerName: any): string;
export function getLambdaLayerHashOutputLogicalId(layerName: any): string;
export function getLambdaLayerS3KeyOutputLogicalId(layerName: any): string;
export function getWebsocketsApiName(): string;
export function getWebsocketsApiLogicalId(): string;
export function getWebsocketsIntegrationLogicalId(functionName: any): string;
export function getLambdaWebsocketsPermissionLogicalId(functionName: any): string;
export function getNormalizedWebsocketsRouteKey(route: any): any;
export function getWebsocketsRouteLogicalId(route: any): string;
export function getWebsocketsDeploymentLogicalId(sha: any): string;
export function getWebsocketsRouteResponseLogicalId(route: any): string;
export function getWebsocketsStageLogicalId(): string;
export function getWebsocketsAuthorizerLogicalId(functionName: any): string;
export function getWebsocketsLogGroupLogicalId(): string;
export function getApiGatewayName(): string;
export function generateApiGatewayDeploymentLogicalId(id: any): string;
export function getRestApiLogicalId(): string;
export function getNormalizedAuthorizerName(functionName: any): string;
export function getAuthorizerLogicalId(functionName: any): string;
export function normalizePath(resourcePath: any): any;
export function getResourceLogicalId(resourcePath: any): string;
export function extractResourceId(resourceLogicalId: any): any;
export function normalizeMethodName(methodName: any): string;
export function getMethodLogicalId(resourceId: any, methodName: any): string;
export function getValidatorLogicalId(): string;
export function getModelLogicalId(schemaId: any): string;
export function getEndpointModelLogicalId(resourceId: any, methodName: any, contentType: any): string;
export function getApiKeyLogicalId(apiKeyNumber: any, apiKeyName: any): string;
export function getApiKeyLogicalIdRegex(): RegExp;
export function getUsagePlanLogicalId(name: any): string;
export function getUsagePlanKeyLogicalId(usagePlanKeyNumber: any, usagePlanKeyName: any): string;
export function getStageLogicalId(): string;
export function getApiGatewayLogGroupLogicalId(): string;
export function getDeploymentBucketLogicalId(): string;
export function getDeploymentBucketOutputLogicalId(): string;
export function getDeploymentBucketPolicyLogicalId(): string;
export function normalizeBucketName(bucketName: any): string;
export function getBucketLogicalId(bucketName: any): string;
export function normalizeTopicName(topicName: any): string;
export function getTopicLogicalId(topicName: any): string;
export function getTopicDLQPolicyLogicalId(functionName: any, topicName: any): string;
export function getScheduleId(functionName: any): string;
export function getScheduleLogicalId(functionName: any, scheduleIndex: any): string;
export function getSchedulerScheduleLogicalId(functionName: any, scheduleIndex: any): string;
export function getStreamLogicalId(functionName: any, streamType: any, streamName: any): string;
export function getStreamConsumerName(functionName: any, streamName: any): string;
export function getStreamConsumerLogicalId(streamConsumerName: any): string;
export function getIotLogicalId(functionName: any, iotIndex: any): string;
export function getLambdaIotPermissionLogicalId(functionName: any, iotIndex: any): string;
export function getIotFleetProvisioningLogicalId(functionName: any): string;
export function getLambdaIotFleetProvisioningPermissionLogicalId(functionName: any): string;
export function getCloudWatchEventId(functionName: any): string;
export function getCloudWatchEventLogicalId(functionName: any, cloudWatchIndex: any): string;
export function getCloudWatchLogLogicalId(functionName: any, logsIndex: any): string;
export function getCognitoUserPoolLogicalId(poolId: any): string;
export function getQueueLogicalId(functionName: any, queueName: any): string;
export function getMSKEventLogicalId(functionName: any, clusterName: any, topicName: any): string;
export function getKafkaEventLogicalId(functionName: any, topicName: any): string;
export function getActiveMQEventLogicalId(functionName: any, queueName: any): string;
export function getRabbitMQEventLogicalId(functionName: any, queueName: any): string;
export function getAlbTargetGroupLogicalId(functionName: any, albId: any, multiValueHeaders: any): string;
export function getAlbTargetGroupNameTagValue(functionName: any, albId: any, multiValueHeaders: any): string;
export function generateAlbTargetGroupName(functionName: any, albId: any, multiValueHeaders: any): string;
export function getAlbListenerRuleLogicalId(functionName: any, idx: any): string;
export function getLambdaS3PermissionLogicalId(functionName: any, bucketName: any): string;
export function getLambdaSnsPermissionLogicalId(functionName: any, topicName: any): string;
export function getLambdaSnsSubscriptionLogicalId(functionName: any, topicName: any): string;
export function getLambdaSchedulePermissionLogicalId(functionName: any, scheduleIndex: any): string;
export function getLambdaCloudWatchEventPermissionLogicalId(functionName: any, cloudWatchIndex: any): string;
export function getLambdaApiGatewayPermissionLogicalId(functionName: any): string;
export function getLambdaHttpApiPermissionLogicalId(functionName: any): string;
export function getLambdaFnUrlPermissionLogicalId(functionName: any): string;
export function getLambdaAuthorizerHttpApiPermissionLogicalId(authorizerName: any): string;
export function getLambdaAlexaSkillPermissionLogicalId(functionName: any, alexaSkillIndex: any): string;
export function getLambdaAlexaSmartHomePermissionLogicalId(functionName: any, alexaSmartHomeIndex: any): string;
export function getLambdaCloudWatchLogPermissionLogicalId(functionName: any): string;
export function getLambdaCognitoUserPoolPermissionLogicalId(functionName: any, poolId: any, triggerSource: any): string;
export function getLambdaAlbPermissionLogicalId(functionName: any): string;
export function getLambdaRegisterTargetPermissionLogicalId(functionName: any): string;
export function getCustomResourcesArtifactName(): string;
export function getCustomResourcesRoleLogicalId(): string;
export function getCustomResourceS3HandlerFunctionName(): string;
export function getCustomResourceS3HandlerFunctionLogicalId(): string;
export function getCustomResourceS3ResourceLogicalId(functionName: any): string;
export function getCustomResourceCognitoUserPoolHandlerFunctionName(): string;
export function getCustomResourceCognitoUserPoolHandlerFunctionLogicalId(): string;
export function getCustomResourceCognitoUserPoolResourceLogicalId(functionName: any): string;
export function getCustomResourceEventBridgeHandlerFunctionName(): string;
export function getCustomResourceEventBridgeHandlerFunctionLogicalId(): string;
export function getCustomResourceEventBridgeResourceLogicalId(functionName: any, idx: any): string;
export function getNormalizedResourceName(resourceName: any): string;
export function getEventBridgeEventBusLogicalId(eventBusName: any): string;
export function getEventBridgeRuleLogicalId(ruleName: any): string;
export function getEventBridgeLambdaPermissionLogicalId(functionName: any, idx: any): string;
export function getCustomResourceApiGatewayAccountCloudWatchRoleHandlerFunctionName(): string;
export function getCustomResourceApiGatewayAccountCloudWatchRoleHandlerFunctionLogicalId(): string;
export function getCustomResourceApiGatewayAccountCloudWatchRoleResourceLogicalId(): string;
export function getCloudFrontDistributionLogicalId(): string;
export function getCloudFrontDistributionDomainNameLogicalId(): string;
export function getLambdaAtEdgeInvokePermissionLogicalId(functionName: any): string;
export function getCloudFrontOriginId(originObj: any): string;
export function getCloudFrontCachePolicyLogicalId(cachePolicyName: any): string;
export function getCloudFrontCachePolicyName(cachePolicyName: any): string;
export function getHttpApiName(): string;
export function getHttpApiDescription(): string;
export function getHttpApiLogicalId(): string;
export function getHttpApiStageLogicalId(): string;
export function getHttpApiIntegrationLogicalId(functionName: any): string;
export function getHttpApiRouteLogicalId(routeKey: any): string;
export function getHttpApiAuthorizerLogicalId(authorizerName: any): string;
export function getHttpApiLogGroupLogicalId(): string;
export function getHttpApiLogGroupName(): string;
export function getEcrRepositoryName(): string;
